using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Indprowebbackend.Migrations
{
    /// <inheritdoc />
    public partial class mssqllocal_migration_157 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FullContent",
                columns: table => new
                {
                    FullContentId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Header1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Header2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Header3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Header4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Header5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ContentsGroup1 = table.Column<int>(type: "int", nullable: true),
                    ContentsGroup2 = table.Column<int>(type: "int", nullable: true),
                    ContentsGroup3 = table.Column<int>(type: "int", nullable: true),
                    ContentsGroup4 = table.Column<int>(type: "int", nullable: true),
                    ContentsGroup5 = table.Column<int>(type: "int", nullable: true),
                    Content1Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage1Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText1Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader1Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content2Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage2Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText2Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader2Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content3Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage3Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText3Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader3Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content4Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage4Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText4Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader4Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content5Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage5Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText5Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader5Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content6Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage6Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText6Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader6Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content7Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage7Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText7Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader7Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content8Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage8Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText8Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader8Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content9Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage9Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText9Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader9Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content10Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage10Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText10Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader10Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Author1Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content1Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage1Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText1Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader1Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content2Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage2Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText2Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader2Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content3Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage3Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText3Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader3Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content4Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage4Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText4Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader4Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content5Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage5Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText5Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader5Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content6Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage6Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText6Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader6Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content7Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage7Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText7Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader7Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content8Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage8Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText8Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader8Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content9Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage9Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText9Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader9Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content10Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage10Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText10Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader10Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Author1Group2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content1Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage1Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText1Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader1Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content2Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage2Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText2Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader2Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content3Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage3Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText3Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader3Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content4Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage4Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText4Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader4Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content5Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage5Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText5Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader5Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content6Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage6Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText6Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader6Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content7Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage7Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText7Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader7Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content8Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage8Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText8Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader8Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content9Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage9Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText9Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader9Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content10Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage10Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText10Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader10Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Author1Group3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content1Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage1Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText1Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader1Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content2Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage2Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText2Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader2Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content3Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage3Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText3Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader3Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content4Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage4Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText4Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader4Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content5Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage5Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText5Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader5Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content6Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage6Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText6Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader6Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content7Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage7Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText7Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader7Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content8Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage8Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText8Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader8Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content9Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage9Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText9Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader9Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content10Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage10Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText10Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader10Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Author1Group4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content1Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage1Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText1Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader1Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content2Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage2Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText2Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader2Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content3Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage3Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText3Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader3Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content4Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage4Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText4Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader4Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content5Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage5Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText5Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader5Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content6Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage6Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText6Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader6Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content7Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage7Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText7Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader7Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content8Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage8Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText8Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader8Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content9Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage9Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText9Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader9Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content10Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubImage10Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImageText10Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader10Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Author1Group5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HeaderListItem1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItemsGroup1 = table.Column<int>(type: "int", nullable: true),
                    ListItem1Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem2Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem3Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem4Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem5Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem6Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem7Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem8Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListContent1Group1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Author = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SubHeader3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItems = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem6 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem7 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListItem8 = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FullContent", x => x.FullContentId);
                });

            migrationBuilder.CreateTable(
                name: "NewsPosts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Image = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Date = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Title = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Content = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Quote = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InternalLink = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ExternalLink = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Href = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BlogPostHref = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BlogPostBtnText = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NewsPosts", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FullContent");

            migrationBuilder.DropTable(
                name: "NewsPosts");
        }
    }
}
