// <auto-generated />
using System;
using Indprowebbackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Indprowebbackend.Migrations
{
    [DbContext(typeof(IndprowebbackendContext))]
    partial class IndprowebbackendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Indprowebbackend.DataModels.FullContent", b =>
                {
                    b.Property<int>("FullContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FullContentId"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author1Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author1Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author1Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author1Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author1Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content10Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content10Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content10Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content10Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content10Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content1Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content1Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content1Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content1Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content1Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content2Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content2Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content2Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content2Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content2Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content3Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content3Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content3Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content3Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content3Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content4Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content4Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content4Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content4Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content4Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content5Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content5Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content5Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content5Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content5Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content6Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content6Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content6Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content6Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content6Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content7Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content7Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content7Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content7Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content7Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content8Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content8Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content8Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content8Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content8Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content9Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content9Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content9Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content9Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content9Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContentsGroup1")
                        .HasColumnType("int");

                    b.Property<int?>("ContentsGroup2")
                        .HasColumnType("int");

                    b.Property<int?>("ContentsGroup3")
                        .HasColumnType("int");

                    b.Property<int?>("ContentsGroup4")
                        .HasColumnType("int");

                    b.Property<int?>("ContentsGroup5")
                        .HasColumnType("int");

                    b.Property<string>("Header1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderListItem1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText10Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText10Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText10Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText10Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText10Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText1Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText1Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText1Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText1Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText1Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText2Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText2Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText2Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText2Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText2Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText3Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText3Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText3Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText3Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText3Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText4Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText4Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText4Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText4Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText4Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText5Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText5Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText5Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText5Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText5Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText6Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText6Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText6Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText6Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText6Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText7Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText7Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText7Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText7Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText7Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText8Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText8Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText8Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText8Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText8Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText9Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText9Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText9Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText9Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageText9Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListContent1Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem1Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem2Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem3Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem4Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem5Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem6Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem7Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItem8Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ListItemsGroup1")
                        .HasColumnType("int");

                    b.Property<string>("SubHeader1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader10Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader10Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader10Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader10Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader10Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader1Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader1Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader1Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader1Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader1Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader2Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader2Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader2Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader2Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader2Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader3Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader3Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader3Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader3Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader3Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader4Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader4Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader4Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader4Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader4Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader5Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader5Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader5Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader5Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader5Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader6Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader6Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader6Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader6Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader6Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader7Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader7Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader7Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader7Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader7Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader8Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader8Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader8Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader8Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader8Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader9Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader9Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader9Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader9Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeader9Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage10Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage10Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage10Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage10Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage10Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage1Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage1Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage1Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage1Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage1Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage2Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage2Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage2Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage2Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage2Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage3Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage3Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage3Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage3Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage3Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage4Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage4Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage4Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage4Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage4Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage5Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage5Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage5Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage5Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage5Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage6Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage6Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage6Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage6Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage6Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage7Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage7Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage7Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage7Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage7Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage8Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage8Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage8Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage8Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage8Group5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage9Group1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage9Group2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage9Group3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage9Group4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubImage9Group5")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FullContentId");

                    b.ToTable("FullContent");
                });

            modelBuilder.Entity("Indprowebbackend.DataModels.NewsPosts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlogPostBtnText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogPostHref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewsPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
